INSERT INTO
 organizations
 (
   name,
   name_alphabet
 )
VALUES
  ('ハロー!プロジェクト', 'Hello! Project'),
  ('ハロプロ関西', 'Hello! Project Kansai'),
  ('ハロプロ台湾', 'Taiwan'),
  ('モーニング娘。', 'Morning Musume'),
  ('アンジュルム', 'Angerme'),
  ('スマイレージ', 'S/mileage'),
  ('Juice=Juice', 'Juice=Juice'),
  ('つばきファクトリー', 'Camellia Factory'),
  ('BEYOOOOONDS', 'BEYOOOOONDS'),
  ('CHICA#TETSU', 'CHICA#TETSU'),
  ('雨ノ森 川海', '雨ノ森 川海'),
  ('SeasoningS', 'SeasoningS'),
  ('OCHA NORMA', 'OCHA NORMA'),
  ('太陽とシスコムーン', 'Taiyo & Ciscomoon'),
  ('T&Cボンバー', 'T&C Bomber'),
  ('シェキドル', 'Sheki-Dol'),
  ('W', 'W'),
  ('ココナッツ娘。', 'Coconuts Musume'),
  ('美勇伝', 'v-u-den'),
  ('アイスクリー娘。', 'Ice Creamusume'),
  ('SI☆NA', 'SI☆NA'),
  ('大小姐', 'Da Xiao Jie'),
  ('Berryz工房×℃-ute', 'Berryz Kobo×℃-ute'),
  ('Berryz工房', 'Berryz Kobo'),
  ('℃-ute', '℃-ute'),
  ('カントリー娘。', 'Country Musume'),
  ('カントリー・ガールズ', 'Country Girls'),
  ('こぶしファクトリー', 'Magnolia Factory'),
  ('タンポポ', 'Tanpopo'),
  ('プッチモニ', 'Petitmoni'),
  ('ミニモニ。', 'Minimoni'),
  ('ZYX', 'ZYX'),
  ('モーニング娘。さくら組', 'Morning Musume Sakuragumi'),
  ('モーニング娘。おとめ組', 'Morning Musume Otomegumi'),
  ('あぁ!', 'Aa!'),
  ('Buono!', 'Buono!'),
  ('H.P.オールスターズ', 'H.P. All Stars'),
  ('ハロー!プロジェクト モベキマス', 'Hello! Project MoBeKiMaSu'),
  ('ハロプロ・オールスターズ', 'Hello! Project All Stars')
